---
# Source: media-microservices/charts/user-review-redis/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-review-redis
  name: user-review-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user-review-redis
  template:
    metadata:
      labels:
        service: user-review-redis
        app: user-review-redis
    spec:
      containers:
      - name: "user-review-redis"
        image: docker.io/library/redis:6.2.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        args:
        - /media-microservices/config/redis.conf
        volumeMounts:
        - name: user-review-redis-config
          mountPath: /media-microservices/config/redis.conf
          subPath: redis.conf
      volumes:
      - name: user-review-redis-config
        configMap:
          name: user-review-redis
      hostname: user-review-redis
      restartPolicy: Always
