---
# Source: media-microservices/charts/user-review-redis/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-review-redis
spec:
  type: ClusterIP
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    service: user-review-redis
