---
# Source: media-microservices/charts/review-storage-memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: review-storage-memcached
spec:
  type: ClusterIP
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    service: review-storage-memcached
