---
# Source: media-microservices/charts/movie-info-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: movie-info-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: movie-info-service
