---
# Source: media-microservices/charts/movie-review-redis/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-review-redis
  labels:
    mediamicroservices/service: movie-review-redis
data:
  redis.conf: |    
    io-threads 8
    io-threads-do-reads yes
    port 6379
    tls-port 0
    
    tls-cert-file /keys/server.crt
    tls-key-file /keys/server.key
    
    tls-auth-clients no
