---
# Source: media-microservices/charts/review-storage-service/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: review-storage-service
  name: review-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: review-storage-service
  template:
    metadata:
      labels:
        service: review-storage-service
        app: review-storage-service
    spec:
      containers:
      - name: "review-storage-service"
        image: docker.io/yg397/media-microservices:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        command:
        - ReviewStorageService
        volumeMounts:
        - name: review-storage-service-config
          mountPath: /media-microservices/config/jaeger-config.yml
          subPath: jaeger-config.yml
        - name: review-storage-service-config
          mountPath: /media-microservices/config/service-config.json
          subPath: service-config.json
      volumes:
      - name: review-storage-service-config
        configMap:
          name: review-storage-service
      hostname: review-storage-service
      restartPolicy: Always
