---
# Source: media-microservices/charts/review-storage-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: review-storage-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: review-storage-service
