---
# Source: media-microservices/charts/nginx-web-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-server
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: nginx-web-server
