---
# Source: media-microservices/charts/review-storage-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: review-storage-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: review-storage-mongodb
