apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: unique-id-service
  name: unique-id-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: unique-id-service
  template:
    metadata:
      labels:
        app: unique-id-service
        service: unique-id-service
    spec:
      containers:
      - command:
        - UniqueIdService
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        name: unique-id-service
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/jaeger-config.yml
          name: unique-id-service-config
          subPath: jaeger-config.yml
        - mountPath: /social-network-microservices/config/service-config.json
          name: unique-id-service-config
          subPath: service-config.json
      hostname: unique-id-service
      restartPolicy: Always
      schedulerName: poseidon
      volumes:
      - configMap:
          name: unique-id-service
        name: unique-id-service-config
