apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: user-timeline-service
  name: user-timeline-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: user-timeline-service
  template:
    metadata:
      labels:
        app: user-timeline-service
        service: user-timeline-service
    spec:
      containers:
      - command:
        - UserTimelineService
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        name: user-timeline-service
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/jaeger-config.yml
          name: user-timeline-service-config
          subPath: jaeger-config.yml
        - mountPath: /social-network-microservices/config/service-config.json
          name: user-timeline-service-config
          subPath: service-config.json
      hostname: user-timeline-service
      restartPolicy: Always
      schedulerName: poseidon
      volumes:
      - configMap:
          name: user-timeline-service
        name: user-timeline-service-config
