---
# Source: media-microservices/charts/movie-info-memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: movie-info-memcached
spec:
  type: ClusterIP
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    service: movie-info-memcached
