apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        service: jaeger
    spec:
      containers:
      - env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: '9411'
        image: docker.io/jaegertracing/all-in-one:latest
        imagePullPolicy: IfNotPresent
        name: jaeger
        ports:
        - containerPort: 5775
        - containerPort: 6831
        - containerPort: 6832
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 9411
        volumeMounts:
        - mountPath: /media-microservices/config/jaeger-config.yml
          name: jaeger-config
          subPath: jaeger-config.yml
        - mountPath: /media-microservices/config/service-config.json
          name: jaeger-config
          subPath: service-config.json
      hostname: jaeger
      restartPolicy: Always
      schedulerName: descheduler
      volumes:
      - configMap:
          name: jaeger
        name: jaeger-config
