apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: media-memcached
  name: media-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      service: media-memcached
  template:
    metadata:
      labels:
        app: media-memcached
        service: media-memcached
    spec:
      containers:
      - image: docker.io/library/memcached:1.6.7
        imagePullPolicy: IfNotPresent
        name: media-memcached
        ports:
        - containerPort: 11211
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/jaeger-config.yml
          name: media-memcached-config
          subPath: jaeger-config.yml
        - mountPath: /social-network-microservices/config/service-config.json
          name: media-memcached-config
          subPath: service-config.json
      hostname: media-memcached
      restartPolicy: Always
      schedulerName: poseidon
      volumes:
      - configMap:
          name: media-memcached
        name: media-memcached-config
