---
# Source: media-microservices/charts/plot-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plot-service
spec:
  type: ClusterIP
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    service: plot-service
