---
# Source: media-microservices/charts/movie-review-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: movie-review-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: movie-review-mongodb
