---
# Source: media-microservices/charts/plot-mongodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plot-mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    service: plot-mongodb
