apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: compose-post-service
  name: compose-post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: compose-post-service
  template:
    metadata:
      labels:
        app: compose-post-service
        service: compose-post-service
    spec:
      containers:
      - command:
        - ComposePostService
        image: docker.io/deathstarbench/social-network-microservices:latest
        imagePullPolicy: IfNotPresent
        name: compose-post-service
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/jaeger-config.yml
          name: compose-post-service-config
          subPath: jaeger-config.yml
        - mountPath: /social-network-microservices/config/service-config.json
          name: compose-post-service-config
          subPath: service-config.json
      hostname: compose-post-service
      restartPolicy: Always
      schedulerName: descheduler
      volumes:
      - configMap:
          name: compose-post-service
        name: compose-post-service-config
