---
# Source: media-microservices/charts/cast-info-memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cast-info-memcached
spec:
  type: ClusterIP
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    service: cast-info-memcached
