apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: social-graph-redis
  name: social-graph-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: social-graph-redis
  template:
    metadata:
      labels:
        app: social-graph-redis
        service: social-graph-redis
    spec:
      containers:
      - args:
        - /social-network-microservices/config/redis.conf
        image: docker.io/library/redis:6.2.4
        imagePullPolicy: IfNotPresent
        name: social-graph-redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/redis.conf
          name: social-graph-redis-config
          subPath: redis.conf
      hostname: social-graph-redis
      restartPolicy: Always
      schedulerName: poseidon
      volumes:
      - configMap:
          name: social-graph-redis
        name: social-graph-redis-config
