---
# Source: media-microservices/charts/plot-memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: plot-memcached
spec:
  type: ClusterIP
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  selector:
    service: plot-memcached
