apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: url-shorten-mongodb
  name: url-shorten-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: url-shorten-mongodb
  template:
    metadata:
      labels:
        app: url-shorten-mongodb
        service: url-shorten-mongodb
    spec:
      containers:
      - args:
        - --config
        - /social-network-microservices/config/mongod.conf
        image: docker.io/library/mongo:4.4.6
        imagePullPolicy: IfNotPresent
        name: url-shorten-mongodb
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /social-network-microservices/config/mongod.conf
          name: url-shorten-mongodb-config
          subPath: mongod.conf
      hostname: url-shorten-mongodb
      restartPolicy: Always
      schedulerName: descheduler
      volumes:
      - configMap:
          name: url-shorten-mongodb
        name: url-shorten-mongodb-config
